services:
  - type: web
    name: eyesunclouded-portfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - fromDotEnv: true
