services:
  # ——————————————————————————————————————————————
  # 1) Flask UI
  - type: web
    name: eyesuncloudedportfolio      # subdomain: eyesuncloudedportfolio.onrender.com
    env: python
    branch: main
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:

    envVars:
      - fromDotEnv: true
    healthCheckPath: /status

  # ——————————————————————————————————————————————
  # 2) Cloelia FastAPI agent
  - type: web
    name: cloelia-api                 # subdomain: cloelia-api.onrender.com
    env: python
    branch: main
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn cloelia_api:app --host=0.0.0.0 --port 

    envVars:
      - fromDotEnv: true
    healthCheckPath: /healthz
